return {
    "Arch. Petasos +1",
    "Arch. Gloves +1",
    "Wicce Petasos +1",
    "Wicce Coat +1",
    "Wicce Gloves +1",
    "Wicce Chausses +1",
    "Wicce Sabots +1",
    "Spaekona's Coat +2",
    "Spae. Gloves +2",
    "Arch. Coat +3",
    "Arch. Tonban +3",
    "Mallquis Clogs +1",
    "Mallquis Chapeau +1",
    "Mallquis Saio +1",
    "Mallquis Cuffs +1",
    "Mallquis Trews +1",
    "Jhakri Robe +2",
    "Jhakri Cuffs +2",
    "Jhakri Slops +2",
    "Mallquis Ring",
    "Jhakri Ring",
}
