return {
    "Atro. Chapeau +1",
    "Jhakri Cuffs +2",
    "Pill. Bonnet +1",
    "Viti. Tights +1",
    "Pillager's Vest +1",
    "Atrophy Gloves +2",
    "Lethargy Sayon +1",
    "Atrophy Tabard +2",
    "Atrophy Tights +2",
    "Jhakri Slops +2",
    "Jhakri Robe +2",
    "Pill. Armlets +1",
    "Pill. Culottes +1",
    "Pill. Poulaines +1",
    "Plun. Bonnet +1",
    "Plunderer's Vest +1",
    "Plun. Armlets +1",
    "Atrophy Boots +1",
    "Plun. Culottes +1",
    "Plun. Poulaines +1",
    "Skulk. Poulaines +1",
    "Meg. Cuirie +2",
    "Leth. Chappel +1",
    "Meg. Gloves +2",
    "Meg. Chausses +2",
    "Leth. Gantherots +1",
    "Mummu Bonnet +2",
    "Leth. Fuseau +1",
    "Leth. Houseaux +1",
    "Mummu Jacket +2",
    "Viti. Chapeau +3",
    "Mummu Kecks +2",
    "Meghanada Ring",
    "Mummu Ring",
    "Ayanmo Corazza +2",
    "Aya. Manopolas +2",
    "Viti. Gloves +1",
    "Vitiation Boots +2",
    "Viti. Tabard +3",
}
