return {
    "Atro. Chapeau +1",
    "Jhakri Cuffs +2",
    "Viti. Tights +1",
    "Atrophy Gloves +2",
    "Lethargy Sayon +1",
    "Atrophy Tabard +2",
    "Atrophy Tights +2",
    "Jhakri Slops +2",
    "Jhakri Robe +2",
    "Atrophy Boots +1",
    "Leth. Chappel +1",
    "Leth. Gantherots +1",
    "Leth. Fuseau +1",
    "Leth. Houseaux +1",
    "Viti. Chapeau +3",
    "Ayanmo Corazza +2",
    "Aya. Manopolas +2",
    "Viti. Gloves +1",
    "Vitiation Boots +2",
    "Viti. Tabard +3",
}
