return {
    "Azimuth Hood +1",
    "Azimuth Coat +1",
    "Azimuth Gaiters +1",
    "Geomancy Tunic +2",
    "Geo. Mitaines +2",
    "Geomancy Pants +2",
    "Geo. Sandals +2",
    "Bagua Tunic +3",
    "Bagua Mitaines +3",
    "Bagua Pants +3",
    "Bagua Sandals +3",
    "Jhakri Cuffs +2",
    "Jhakri Slops +2",
    "Jhakri Robe +2",
	"Jhakri Pigaches +2",
    "Mallquis Clogs +1",
    "Mallquis Chapeau +1",
    "Mallquis Saio +1",
    "Mallquis Cuffs +1",
    "Mallquis Trews +2",
}
