return {
	"Hachiya Hatsuburi +1",
	"Hachiya Chainmail +1",
	"Hachiya Tekko +1",
	"Hachiya Hakama +1",
	"Hachiya Kyahan +1",
	"Mochizuki Hatsuburi +1",
	"Mochizuki Chainmail +1",
	"Mochizuki Tekko +1",
	"Mochizuki Hakama +1",
	"Mochizuki Kyahan +1",
	"Hizamaru Somen +1",
	"Hizamaru Haramaki +1",
	"Hizamaru Kote +1",
	"Hizamaru Hizayoroi +1",
	"Hizamaru Sune-Ate +1",
	"Mummu Bonnet +2",
	"Mummu Jacket +2",
	"Mummu Wrists +1",
	"Mummu Kecks +2",
	"Mummu Gamashes +1"
}
