return {
    "Pill. Bonnet +1",
    "Pillager's Vest +1",
    "Pill. Armlets +1",
    "Pill. Culottes +1",
    "Pill. Poulaines +1",
    "Plun. Bonnet +1",
    "Plunderer's Vest +1",
    "Plun. Armlets +1",
    "Plun. Culottes +1",
    "Plun. Poulaines +1",
    "Skulk. Poulaines +1",
    "Meg. Cuirie +2",
    "Meg. Gloves +2",
    "Meg. Chausses +2",
    "Mummu Bonnet +2",
    "Mummu Jacket +2",
    "Mummu Kecks +2",
    "Meghanada Ring",
    "Mummu Ring",
}
