return {
    "Theo. Briault +1",
    "Theo. Pant. +1",
    "Theo. Duckbills +1",
    "Piety Cap +2",
    "Piety Briault +3",
    "Piety Duckbills +2",
    "Piety Pantaln. +3",
	"Piety Mitts +3",
    "Ebers Cap +1",
    "Ebers Bliaud +1",
	"Ebers Mitts +1",
    "Ebers Pant. +1",
	"Ebers Duckbills +1",
    "Ayanmo Corazza +2",
    "Aya. Manopolas +2",
}
