return {
    "Theo. Briault +1",
    "Theo. Pant. +1",
    "Theo. Duckbills +1",
    "Piety Cap +1",
    "Piety Briault +1",
    "Piety Pantaln. +1",
    "Piety Duckbills +1",
	"Piety Mitts +3",
    "Ebers Cap +1",
    "Ebers Bliaud +1",
    "Ebers Pant. +1",
    "Ayanmo Corazza +2",
    "Aya. Manopolas +2",
}
